name: IpaToolMac
options:
  bundleIdPrefix: com.ipatool
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  defaultConfig: Debug
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: "5.7.1"
  FMDB:
    url: https://github.com/ccgus/fmdb
    from: "2.7.12"
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: NO
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    COMBINE_HIDPI_IMAGES: YES
targets:
  IpaToolMac:
    type: application
    platform: macOS
    productName: IPA Tool
    sources:
      - path: IpaToolMac
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: SnapKit
        product: SnapKit
      - package: FMDB
        product: FMDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ipatool.mac
        PRODUCT_NAME: IPA Tool
        MARKETING_VERSION: "1.0.2"
        CURRENT_PROJECT_VERSION: "4"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: IPA Tool
        INFOPLIST_KEY_CFBundleName: IPA Tool
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_LSMinimumSystemVersion: "13.0"
        INFOPLIST_KEY_NSHighResolutionCapable: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "ipatool is MIT licensed"
        INFOPLIST_KEY_CFBundleDevelopmentRegion: zh-Hans
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
schemes:
  IpaToolMac:
    build:
      targets:
        IpaToolMac: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
